name: Make Workflow
run-name: ${{ github.actor }} is running Make Workflow ğŸš€
on: [push]
jobs:
  Make-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸  The workflow is now ready to test your code on the runner."
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need
      - name: Install PostgreSQL
        run: sudo apt-get install -y postgresql postgresql-contrib
      - name: Set up PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE mydatabase;"
          sudo -u postgres psql -c "CREATE USER myuser WITH PASSWORD 'mypassword';"
          sudo -u postgres psql -c "ALTER ROLE myuser SET client_encoding 'utf8';"
          sudo -u postgres psql -c "ALTER ROLE myuser SET default_transaction_isolation TO 'read committed';"
          sudo -u postgres psql -c "ALTER ROLE myuser SET timezone TO 'UTC';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;"
      - name: Set up virtual environment
        run: python -m venv venv
      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with necessary dependencies
      - name: Change directory and run make django-init-wagtail
        run: |
          cd test/django-init-wagtail
          source ../../venv/bin/activate
          make django-init-wagtail
      - run: echo "ğŸ This job's status is ${{ job.status }}."
